/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import Entity.department;
import Entity.department;
import Entity.employee;
import Entity.employee_phones;
import Entity.project;
import Entity.workOn;
import company.Tools;

/**
 *
 * @author Wafaa
 */
public class frtest extends javax.swing.JFrame {

    /**
     * Creates new form frtest
     */
    public frtest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntest = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        m = new javax.swing.JTable();
        btnTestEmp = new javax.swing.JButton();
        btnTestPhones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btntest.setText("jButton1");
        btntest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestActionPerformed(evt);
            }
        });

        m.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(m);

        btnTestEmp.setText("test Employee");
        btnTestEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestEmpActionPerformed(evt);
            }
        });

        btnTestPhones.setText("test phones");
        btnTestPhones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestPhonesActionPerformed(evt);
            }
        });

        jButton1.setText("Test Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("workon");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTestEmp)
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btntest)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnTestPhones)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnTestPhones))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntest)
                            .addComponent(jButton2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(38, 38, 38)
                .addComponent(btnTestEmp)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestActionPerformed
        department obj =new department();
        obj.setDeptNo(1);
        //obj.setDeptName("is cs56");
        //obj.setLocation("Giza");
        //obj.delete();
        //obj.add();
        //obj.getAllRows(m);
        //Tools.msgBox(obj.getValueByName("is cs56"));
        Tools.msgBox(obj.getNameByValue("3"));
    }//GEN-LAST:event_btntestActionPerformed

    private void btnTestEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestEmpActionPerformed
        // TODO add your handling code here:
        employee obj =new employee();
        obj.setEmpNo(4);
        //obj.setEmpName("sakrrfte");
        //obj.setAddress("Alexrfe");
       // obj.setSalary(1200);
       // obj.setHiringDate("2015-05-03");
        //obj.setBirthDate("1999-06-01");
        //obj.setDeptNo(1);
       // obj.add();
       //obj.delete();
       //obj.getAllRows(m);
       //Tools.msgBox(obj.getNameByValue("1"));
       //Tools.msgBox(obj.getValueByName("Sakr"));
       obj.getOnerows(m);

      // obj.getCustomRow("select * from employee_data", m);
       //Tools.msgBox(obj.getAutoNumber());
        
        
    }//GEN-LAST:event_btnTestEmpActionPerformed

    private void btnTestPhonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestPhonesActionPerformed
        // TODO add your handling code here:
        employee_phones obj=new employee_phones();
        obj.setEmpno(1);
        obj.setPhones("4564343633464");
        obj.add();
        //obj.deletebyemp();
        obj.getAllRows(m);
    }//GEN-LAST:event_btnTestPhonesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        project obj=new project();
        obj.setProjectno(1);
        obj.setProjectNAme("saaaaakr");
        obj.setProjectLocation("aaaalex");
        obj.setDeptno(1);
        //obj.update();
        //obj.delete();
        //Tools.msgBox(obj.getAutoNumber());
        //obj.getOnerows(m);
        //obj.getCustomRow("Select * from project_data where project_no =1", m);
        Tools.msgBox(obj.getNameByValue("1"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        workOn obj=new workOn();
        obj.setEmpNo(1);
        obj.setProjectNo(1);
        //obj.add();
        //obj.delete();
        //obj.getOnerows(m);
        obj.getCustomRow("select * from workon_data ", m);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frtest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frtest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTestEmp;
    private javax.swing.JButton btnTestPhones;
    private javax.swing.JButton btntest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable m;
    // End of variables declaration//GEN-END:variables
}
